#can be many wiki & many www sites

[server]
port = 3000
addr = "0.0.0.0"

[[wiki]]
#unique name for the wiki
name = "matchmakers"
#http or git url
url = "git@github.com:threefoldfoundation/info_matchmakers.git"
#if empty will be auto created
path = ""
#commit automatically when there is new info, only works when ssh used
autocommit = false
#branch name, of "" then will be the default or what is found on the FS
branch = "development"
#switch branch automatically if the name given above and its different on FS
branchswitch = false
#path in the repo where the info is, std "src"
srcdir = "src"
#environment name (for example:  production, staging, test), is used to define location where code will be checked out is ~/$environment/code/... 
#if empty then is ~/sandbox/code
environment = "testing"
auth = true


[[wiki]]
name = "ambassadors"
url = "git@github.com:threefoldfoundation/info_ambassadors.git"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"
auth = true

[[wiki]]
name = "advisors"
url = "git@github.com:threefoldfoundation/info_advisors.git"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"
auth = true

[[wiki]]
name = "board"
url = "git@github.com:threefoldfoundation/info_board.git"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"
auth = true

[[wiki]]
name = "news"
url = "git@github.com:threefoldfoundation/info_tf_news.git"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"
auth = true

[[wiki]]
name = "sdk"
title = "Grid Manual"
url = "git@github.com:threefoldfoundation/info_tfgridsdk.git"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"

[[wiki]]
name = "wiki"
title = "ThreeFold Wiki Staging"
#http or git url
url = "git@github.com:threefoldfoundation/info_threefold.git"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"

#website
[[www]]
name = "freetft"
url = "git@github.com:threefoldfoundation/www_getfreetft.git"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = ""
environment = "testing"


#website
[[www]]
name = "threefold"
url = "git@github.com:threefoldfoundation/www_threefold.io_new.git"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = "html"
environment = "testing"

[[www]]
name = "incubaid"
url = "git@github.com:Incubaid/www_incubaid.git"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = ""
environment = "testing"

#website
[[www]]
name = "freeflownation"
url = "git@github.com:freeflownation/www_freeflownation"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = "html"
environment = "testing"


#data of simulator exports
[[data]]
name = "simexports"
title = "Simulator data repo"
url = "git@github.com:threefoldfoundation/simulator_export"
path = ""
autocommit = false
branch = "master"
branchswitch = true
srcdir = "src"
environment = "testing"

#data for conscious internet
[[data]]
name = "ecosystemdata"
title = "conscious internet data"
url = "git@github.com:threefoldfoundation/www_threefold_ecosystem"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = ""
environment = "testing"

[[blog]]
name = "tfblog"
title = "Threefold Blog"
url = "https://github.com/threefoldfoundation/blog_threefold"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = ""
#environment name (for example:  production, staging, testing)
environment = "testing"
domain = "blog2.threefold.io"

