#can be many wiki & many www sites

[server]
port = 3000
addr = "0.0.0.0"



[[wiki]]
name = "news"
url = "git@github.com:threefoldfoundation/info_tf_news.git"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"
auth = true

[[wiki]]
name = "sdk"
title = "Grid Manual"
url = "git@github.com:threefoldfoundation/info_tfgridsdk.git"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = "testing"


#website
[[www]]
name = "freeflownation"
url = "git@github.com:freeflownation/www_freeflownation"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = "html"
environment = "testing"




[[blog]]
name = "tfblog"
title = "Threefold Blog"
url = "https://github.com/threefoldfoundation/blog_threefold"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = ""
#environment name (for example:  production, staging, testing)
environment = "testing"
domain = "blog2.threefold.io
