#can be many wiki & many www sites

[server]
port = 3000
addr = "0.0.0.0"

[[wiki]]
name = "wiki"
url = "git@github.com:threefoldfoundation/info_threefold.git"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = ""

[[wiki]]
name = "sdk"
title = "Grid Manual"
url = "git@github.com:threefoldfoundation/info_tfgridsdk.git"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "src"
environment = ""

[[wiki]]
name = "marketplace"
title = "Marketplace Manual"
url = "git@github.com:threefoldfoundation/info_manual_tfgrid_testnet.git"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "src"
environment = ""


[[wiki]]
name = "publishingtools"
title = "publishingtools"
url = "git@github.com:crystaluniverse/publishingtools.git"
path = ""
autocommit = false
branch = "development"
branchswitch = false
srcdir = "mydocs"
environment = ""


[[wiki]]
name = "crystaltools"
title = "crystaltools"
url = "git@github.com:crystaluniverse/crystaltools.git"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "mydocs"
environment = ""


#website
[[www]]
name = "freeflownation"
url = "git@github.com:freeflownation/www_freeflownation"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = "html"
environment = ""


[[blog]]
name = "tfblog"
title = "Threefold Blog"
url = "https://github.com/threefoldfoundation/blog_threefold"
path = ""
autocommit = false
branch = "development"
branchswitch = true
srcdir = ""
#environment name (for example:  production, staging, testing)
environment = ""
domain = "blog2.threefold.io"
